language: python
# install hugo from source
install:
    - wget https://github.com/gohugoio/hugo/releases/download/v0.54.0/hugo_0.54.0_Linux-64bit.deb
#    - wget https://github.com/gohugoio/hugo/releases/download/v0.54.0/hugo_extended_0.54.0_Linux-64bit.deb
    - sudo dpkg -i hugo*.deb
    - sudo apt-get install libstdc++6
    - pip install Pygments

#build hugo page
script:
    - hugo

# Deploy to GitHub pages
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: public
  fqdn: www.kg-etechnik.de
  on:
    branch: master
