backend:
  name: github
  repo: Shogoki/etechnik-hugo # Path to your GitHub repository
  base_url: https://oauth.srv2.evolution-web.de/

#publish_mode: editorial_workflow

# These lines should *not* be indented
media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: "locations"
    label: "Kursorte"
    folder: "content/locations"
    create: true
    slug:  "{{slug}}" 
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "locations"}
      - {label: "Titel", name: "title", widget: "string"}
      - {label: "Ort", name: "location", widget: "string"}
      - {label: "Kontaktdaten", name: "body", widget: "markdown"}
  - name: "team"
    label: "Team Mitglied"
    folder: "content/team"
    create: true
    slug:  "{{slug}}" 
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "team"}
      - {label: "Name", name: "title", widget: "string"}
      - {label: "Geboren", name: "birth", widget: "string", required: false}
      - {label: "E-mail", name: "mail", widget: "string", required: false}
      - {label: "Telefon", name: "phone", widget: "string", required: false}
      - {label: "Website", name: "web", widget: "string", required: false}
      - {label: "Adresse", name: "address", widget: "text", required: false}
      - {label: "Bild", name: "image", widget: "image", required: false}
      - {label: "Inhalt", name: "body", widget: "markdown"} #maybe the CV could be done with LIST widget
  - name: "events"
    label: "Termine"
    folder: "content/events"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Kursname", name: "title", widget: "string"}
      - {label: "Kursbeginn", name: "startdate", widget: "date", format: "YYYY-MM-DD"}
      - {label: "Kursende", name: "enddate", widget: "date", format: "YYYY-MM-DD"}
      - {label: "Referent", name: "referent", widget: "string"}
      - {label: "Kosten", name: "cost", widget: "string"}
      - label: "Kursort"
        name: "location"
        widget: "relation"
        collection: "locations"
        searchFields: ["title"]
        valueField: "title"
        displayFields: ["title"] 
  - name: "pages" # Used in routes, e.g., /admin/collections/blog
    label: "Seiten" # Used in the UI
    folder: "content/pages" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" #"{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "pages"}
      - {label: "Titel", name: "title", widget: "string"}
#     - {label: "Publish Date", name: "date", widget: "datetime"}
      - label: "Menü"
        name: "menu"
        widget: "object"
        fields:
          - label: "Hauptmenü"
            name: "main"
            widget: "object"
            fields: 
              - label: "Übergeordnet"
                name: "parent"
                widget: "relation"
                collection: "pages"
                searchFields: ["title"]
                valueField: "title"
                displayFields: ["title"] 
      #- {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Inhalt", name: "body", widget: "markdown"}
  - name: "endpages" # Used in routes, e.g., /admin/collections/blog
    label: "Endseiten" # Used in the UI
    folder: "content/endpages" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" #"{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "pages"}
      - {label: "Titel", name: "title", widget: "string"}
#     - {label: "Publish Date", name: "date", widget: "datetime"}
      - label: "Menü"
        name: "menu"
        widget: "object"
        fields:
          - label: "Menüende"
            name: "end"
            widget: "object"
            fields: 
              - label: "Übergeordnet"
                name: "parent"
                widget: "relation"
                collection: "endpages"
                searchFields: ["title"]
                valueField: "title"
                displayFields: ["title"] 
      #- {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Inhalt", name: "body", widget: "markdown"}